language: java

notifications:
  email:
    recipents:
      - juani.murano@gmail.com
      - marconidaniel@outlook.com
      - danielmarconi91@gmail.com
      - elwindwalker@gmail.com
    on_success: always
    on_failure: always